// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetric.proto

package org.tracing.network.language.metric;

/**
 * <pre>
 * See: https://docs.oracle.com/javase/8/docs/api/java/lang/management/ClassLoadingMXBean.html
 * </pre>
 *
 * Protobuf type {@code deeptracing.v1.Class}
 */
public final class Class extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deeptracing.v1.Class)
    ClassOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Class.newBuilder() to construct.
  private Class(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Class() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Class();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JVMMetricOuterClass.internal_static_deeptracing_v1_Class_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JVMMetricOuterClass.internal_static_deeptracing_v1_Class_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Class.class, Builder.class);
  }

  public static final int LOADEDCLASSCOUNT_FIELD_NUMBER = 1;
  private long loadedClassCount_ = 0L;
  /**
   * <code>int64 loadedClassCount = 1;</code>
   * @return The loadedClassCount.
   */
  @Override
  public long getLoadedClassCount() {
    return loadedClassCount_;
  }

  public static final int TOTALUNLOADEDCLASSCOUNT_FIELD_NUMBER = 2;
  private long totalUnloadedClassCount_ = 0L;
  /**
   * <code>int64 totalUnloadedClassCount = 2;</code>
   * @return The totalUnloadedClassCount.
   */
  @Override
  public long getTotalUnloadedClassCount() {
    return totalUnloadedClassCount_;
  }

  public static final int TOTALLOADEDCLASSCOUNT_FIELD_NUMBER = 3;
  private long totalLoadedClassCount_ = 0L;
  /**
   * <code>int64 totalLoadedClassCount = 3;</code>
   * @return The totalLoadedClassCount.
   */
  @Override
  public long getTotalLoadedClassCount() {
    return totalLoadedClassCount_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (loadedClassCount_ != 0L) {
      output.writeInt64(1, loadedClassCount_);
    }
    if (totalUnloadedClassCount_ != 0L) {
      output.writeInt64(2, totalUnloadedClassCount_);
    }
    if (totalLoadedClassCount_ != 0L) {
      output.writeInt64(3, totalLoadedClassCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (loadedClassCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, loadedClassCount_);
    }
    if (totalUnloadedClassCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, totalUnloadedClassCount_);
    }
    if (totalLoadedClassCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, totalLoadedClassCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Class)) {
      return super.equals(obj);
    }
    Class other = (Class) obj;

    if (getLoadedClassCount()
        != other.getLoadedClassCount()) return false;
    if (getTotalUnloadedClassCount()
        != other.getTotalUnloadedClassCount()) return false;
    if (getTotalLoadedClassCount()
        != other.getTotalLoadedClassCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOADEDCLASSCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLoadedClassCount());
    hash = (37 * hash) + TOTALUNLOADEDCLASSCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalUnloadedClassCount());
    hash = (37 * hash) + TOTALLOADEDCLASSCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalLoadedClassCount());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Class parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Class parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Class parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Class parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Class parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Class parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Class parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Class parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Class parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Class parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Class parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Class parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Class prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * See: https://docs.oracle.com/javase/8/docs/api/java/lang/management/ClassLoadingMXBean.html
   * </pre>
   *
   * Protobuf type {@code deeptracing.v1.Class}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deeptracing.v1.Class)
          ClassOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JVMMetricOuterClass.internal_static_deeptracing_v1_Class_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JVMMetricOuterClass.internal_static_deeptracing_v1_Class_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Class.class, Builder.class);
    }

    // Construct using org.network.language.jvmmetric.Class.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      loadedClassCount_ = 0L;
      totalUnloadedClassCount_ = 0L;
      totalLoadedClassCount_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JVMMetricOuterClass.internal_static_deeptracing_v1_Class_descriptor;
    }

    @Override
    public Class getDefaultInstanceForType() {
      return Class.getDefaultInstance();
    }

    @Override
    public Class build() {
      Class result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Class buildPartial() {
      Class result = new Class(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Class result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.loadedClassCount_ = loadedClassCount_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalUnloadedClassCount_ = totalUnloadedClassCount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalLoadedClassCount_ = totalLoadedClassCount_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Class) {
        return mergeFrom((Class)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Class other) {
      if (other == Class.getDefaultInstance()) return this;
      if (other.getLoadedClassCount() != 0L) {
        setLoadedClassCount(other.getLoadedClassCount());
      }
      if (other.getTotalUnloadedClassCount() != 0L) {
        setTotalUnloadedClassCount(other.getTotalUnloadedClassCount());
      }
      if (other.getTotalLoadedClassCount() != 0L) {
        setTotalLoadedClassCount(other.getTotalLoadedClassCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              loadedClassCount_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              totalUnloadedClassCount_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              totalLoadedClassCount_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long loadedClassCount_ ;
    /**
     * <code>int64 loadedClassCount = 1;</code>
     * @return The loadedClassCount.
     */
    @Override
    public long getLoadedClassCount() {
      return loadedClassCount_;
    }
    /**
     * <code>int64 loadedClassCount = 1;</code>
     * @param value The loadedClassCount to set.
     * @return This builder for chaining.
     */
    public Builder setLoadedClassCount(long value) {

      loadedClassCount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 loadedClassCount = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoadedClassCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      loadedClassCount_ = 0L;
      onChanged();
      return this;
    }

    private long totalUnloadedClassCount_ ;
    /**
     * <code>int64 totalUnloadedClassCount = 2;</code>
     * @return The totalUnloadedClassCount.
     */
    @Override
    public long getTotalUnloadedClassCount() {
      return totalUnloadedClassCount_;
    }
    /**
     * <code>int64 totalUnloadedClassCount = 2;</code>
     * @param value The totalUnloadedClassCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalUnloadedClassCount(long value) {

      totalUnloadedClassCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalUnloadedClassCount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalUnloadedClassCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalUnloadedClassCount_ = 0L;
      onChanged();
      return this;
    }

    private long totalLoadedClassCount_ ;
    /**
     * <code>int64 totalLoadedClassCount = 3;</code>
     * @return The totalLoadedClassCount.
     */
    @Override
    public long getTotalLoadedClassCount() {
      return totalLoadedClassCount_;
    }
    /**
     * <code>int64 totalLoadedClassCount = 3;</code>
     * @param value The totalLoadedClassCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalLoadedClassCount(long value) {

      totalLoadedClassCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalLoadedClassCount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalLoadedClassCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalLoadedClassCount_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:deeptracing.v1.Class)
  }

  // @@protoc_insertion_point(class_scope:deeptracing.v1.Class)
  private static final Class DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Class();
  }

  public static Class getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Class>
      PARSER = new com.google.protobuf.AbstractParser<Class>() {
    @Override
    public Class parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Class> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Class> getParserForType() {
    return PARSER;
  }

  @Override
  public Class getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

