// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetric.proto

package org.tracing.network.language.metric;

public interface GCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.GC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.deeptracing.v1.GCPhase phase = 1;</code>
   * @return The enum numeric value on the wire for phase.
   */
  int getPhaseValue();
  /**
   * <code>.deeptracing.v1.GCPhase phase = 1;</code>
   * @return The phase.
   */
  GCPhase getPhase();

  /**
   * <code>int64 count = 2;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>int64 time = 3;</code>
   * @return The time.
   */
  long getTime();
}
