// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetric.proto

package org.tracing.network.language.metric;

import org.tracing.network.language.common.CPU;
import org.tracing.network.language.common.CPUOrBuilder;

public interface JVMMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.JVMMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>.deeptracing.v1.CPU cpu = 2;</code>
   * @return Whether the cpu field is set.
   */
  boolean hasCpu();
  /**
   * <code>.deeptracing.v1.CPU cpu = 2;</code>
   * @return The cpu.
   */
  CPU getCpu();
  /**
   * <code>.deeptracing.v1.CPU cpu = 2;</code>
   */
  CPUOrBuilder getCpuOrBuilder();

  /**
   * <code>repeated .deeptracing.v1.Memory memory = 3;</code>
   */
  java.util.List<Memory>
      getMemoryList();
  /**
   * <code>repeated .deeptracing.v1.Memory memory = 3;</code>
   */
  Memory getMemory(int index);
  /**
   * <code>repeated .deeptracing.v1.Memory memory = 3;</code>
   */
  int getMemoryCount();
  /**
   * <code>repeated .deeptracing.v1.Memory memory = 3;</code>
   */
  java.util.List<? extends MemoryOrBuilder>
      getMemoryOrBuilderList();
  /**
   * <code>repeated .deeptracing.v1.Memory memory = 3;</code>
   */
  MemoryOrBuilder getMemoryOrBuilder(
      int index);

  /**
   * <code>repeated .deeptracing.v1.MemoryPool memoryPool = 4;</code>
   */
  java.util.List<MemoryPool>
      getMemoryPoolList();
  /**
   * <code>repeated .deeptracing.v1.MemoryPool memoryPool = 4;</code>
   */
  MemoryPool getMemoryPool(int index);
  /**
   * <code>repeated .deeptracing.v1.MemoryPool memoryPool = 4;</code>
   */
  int getMemoryPoolCount();
  /**
   * <code>repeated .deeptracing.v1.MemoryPool memoryPool = 4;</code>
   */
  java.util.List<? extends MemoryPoolOrBuilder>
      getMemoryPoolOrBuilderList();
  /**
   * <code>repeated .deeptracing.v1.MemoryPool memoryPool = 4;</code>
   */
  MemoryPoolOrBuilder getMemoryPoolOrBuilder(
      int index);

  /**
   * <code>repeated .deeptracing.v1.GC gc = 5;</code>
   */
  java.util.List<GC>
      getGcList();
  /**
   * <code>repeated .deeptracing.v1.GC gc = 5;</code>
   */
  GC getGc(int index);
  /**
   * <code>repeated .deeptracing.v1.GC gc = 5;</code>
   */
  int getGcCount();
  /**
   * <code>repeated .deeptracing.v1.GC gc = 5;</code>
   */
  java.util.List<? extends GCOrBuilder>
      getGcOrBuilderList();
  /**
   * <code>repeated .deeptracing.v1.GC gc = 5;</code>
   */
  GCOrBuilder getGcOrBuilder(
      int index);

  /**
   * <code>.deeptracing.v1.Thread thread = 6;</code>
   * @return Whether the thread field is set.
   */
  boolean hasThread();
  /**
   * <code>.deeptracing.v1.Thread thread = 6;</code>
   * @return The thread.
   */
  Thread getThread();
  /**
   * <code>.deeptracing.v1.Thread thread = 6;</code>
   */
  ThreadOrBuilder getThreadOrBuilder();

  /**
   * <code>.deeptracing.v1.Class clazz = 7;</code>
   * @return Whether the clazz field is set.
   */
  boolean hasClazz();
  /**
   * <code>.deeptracing.v1.Class clazz = 7;</code>
   * @return The clazz.
   */
  Class getClazz();
  /**
   * <code>.deeptracing.v1.Class clazz = 7;</code>
   */
  ClassOrBuilder getClazzOrBuilder();
}
