// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetric.proto

package org.tracing.network.language.metric;

public interface JVMMetricCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.JVMMetricCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .deeptracing.v1.JVMMetric metrics = 1;</code>
   */
  java.util.List<JVMMetric>
      getMetricsList();
  /**
   * <code>repeated .deeptracing.v1.JVMMetric metrics = 1;</code>
   */
  JVMMetric getMetrics(int index);
  /**
   * <code>repeated .deeptracing.v1.JVMMetric metrics = 1;</code>
   */
  int getMetricsCount();
  /**
   * <code>repeated .deeptracing.v1.JVMMetric metrics = 1;</code>
   */
  java.util.List<? extends JVMMetricOrBuilder>
      getMetricsOrBuilderList();
  /**
   * <code>repeated .deeptracing.v1.JVMMetric metrics = 1;</code>
   */
  JVMMetricOrBuilder getMetricsOrBuilder(
      int index);

  /**
   * <code>string service = 2;</code>
   * @return The service.
   */
  String getService();
  /**
   * <code>string service = 2;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string serviceInstance = 3;</code>
   * @return The serviceInstance.
   */
  String getServiceInstance();
  /**
   * <code>string serviceInstance = 3;</code>
   * @return The bytes for serviceInstance.
   */
  com.google.protobuf.ByteString
      getServiceInstanceBytes();
}
