// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetric.proto

package org.tracing.network.language.metric;

public interface MemoryPoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.MemoryPool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.deeptracing.v1.PoolType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.deeptracing.v1.PoolType type = 1;</code>
   * @return The type.
   */
  PoolType getType();

  /**
   * <code>int64 init = 2;</code>
   * @return The init.
   */
  long getInit();

  /**
   * <code>int64 max = 3;</code>
   * @return The max.
   */
  long getMax();

  /**
   * <code>int64 used = 4;</code>
   * @return The used.
   */
  long getUsed();

  /**
   * <code>int64 committed = 5;</code>
   * @return The committed.
   */
  long getCommitted();
}
