// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracing.proto

package org.tracing.network.language.tracing;

public interface SegmentCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.SegmentCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  java.util.List<org.tracing.network.language.tracing.SegmentObject> 
      getSegmentsList();
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  org.tracing.network.language.tracing.SegmentObject getSegments(int index);
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  int getSegmentsCount();
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  java.util.List<? extends org.tracing.network.language.tracing.SegmentObjectOrBuilder> 
      getSegmentsOrBuilderList();
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  org.tracing.network.language.tracing.SegmentObjectOrBuilder getSegmentsOrBuilder(
      int index);
}
