// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracing.proto

package org.tracing.network.language.tracing;

/**
 * <pre>
 * Segment reference represents the link between two existing segment.
 * </pre>
 *
 * Protobuf type {@code deeptracing.v1.SegmentReference}
 */
public final class SegmentReference extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deeptracing.v1.SegmentReference)
    SegmentReferenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SegmentReference.newBuilder() to construct.
  private SegmentReference(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentReference() {
    refType_ = 0;
    traceId_ = "";
    parentTraceSegmentId_ = "";
    parentService_ = "";
    parentServiceInstance_ = "";
    parentEndpoint_ = "";
    networkAddressUsedAtPeer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SegmentReference();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentReference_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentReference_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tracing.network.language.tracing.SegmentReference.class, org.tracing.network.language.tracing.SegmentReference.Builder.class);
  }

  public static final int REFTYPE_FIELD_NUMBER = 1;
  private int refType_ = 0;
  /**
   * <pre>
   * Represent the reference type. It could be across thread or across process.
   * Across process means there is a downstream RPC call for this.
   * Typically, refType == CrossProcess means SpanObject#spanType = entry.
   * </pre>
   *
   * <code>.deeptracing.v1.RefType refType = 1;</code>
   * @return The enum numeric value on the wire for refType.
   */
  @java.lang.Override public int getRefTypeValue() {
    return refType_;
  }
  /**
   * <pre>
   * Represent the reference type. It could be across thread or across process.
   * Across process means there is a downstream RPC call for this.
   * Typically, refType == CrossProcess means SpanObject#spanType = entry.
   * </pre>
   *
   * <code>.deeptracing.v1.RefType refType = 1;</code>
   * @return The refType.
   */
  @java.lang.Override public org.tracing.network.language.tracing.RefType getRefType() {
    org.tracing.network.language.tracing.RefType result = org.tracing.network.language.tracing.RefType.forNumber(refType_);
    return result == null ? org.tracing.network.language.tracing.RefType.UNRECOGNIZED : result;
  }

  public static final int TRACEID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <pre>
   * A string id represents the whole trace.
   * </pre>
   *
   * <code>string traceId = 2;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A string id represents the whole trace.
   * </pre>
   *
   * <code>string traceId = 2;</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTTRACESEGMENTID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentTraceSegmentId_ = "";
  /**
   * <pre>
   * Another segment id as the parent.
   * </pre>
   *
   * <code>string parentTraceSegmentId = 3;</code>
   * @return The parentTraceSegmentId.
   */
  @java.lang.Override
  public java.lang.String getParentTraceSegmentId() {
    java.lang.Object ref = parentTraceSegmentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentTraceSegmentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Another segment id as the parent.
   * </pre>
   *
   * <code>string parentTraceSegmentId = 3;</code>
   * @return The bytes for parentTraceSegmentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentTraceSegmentIdBytes() {
    java.lang.Object ref = parentTraceSegmentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentTraceSegmentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTSPANID_FIELD_NUMBER = 4;
  private int parentSpanId_ = 0;
  /**
   * <pre>
   * The span id in the parent trace segment.
   * </pre>
   *
   * <code>int32 parentSpanId = 4;</code>
   * @return The parentSpanId.
   */
  @java.lang.Override
  public int getParentSpanId() {
    return parentSpanId_;
  }

  public static final int PARENTSERVICE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentService_ = "";
  /**
   * <pre>
   * The service logic name of the parent segment.
   * If refType == CrossThread, this name is as same as the trace segment.
   * </pre>
   *
   * <code>string parentService = 5;</code>
   * @return The parentService.
   */
  @java.lang.Override
  public java.lang.String getParentService() {
    java.lang.Object ref = parentService_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentService_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The service logic name of the parent segment.
   * If refType == CrossThread, this name is as same as the trace segment.
   * </pre>
   *
   * <code>string parentService = 5;</code>
   * @return The bytes for parentService.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentServiceBytes() {
    java.lang.Object ref = parentService_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentService_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTSERVICEINSTANCE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentServiceInstance_ = "";
  /**
   * <pre>
   * The service logic name instance of the parent segment.
   * If refType == CrossThread, this name is as same as the trace segment.
   * </pre>
   *
   * <code>string parentServiceInstance = 6;</code>
   * @return The parentServiceInstance.
   */
  @java.lang.Override
  public java.lang.String getParentServiceInstance() {
    java.lang.Object ref = parentServiceInstance_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentServiceInstance_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The service logic name instance of the parent segment.
   * If refType == CrossThread, this name is as same as the trace segment.
   * </pre>
   *
   * <code>string parentServiceInstance = 6;</code>
   * @return The bytes for parentServiceInstance.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentServiceInstanceBytes() {
    java.lang.Object ref = parentServiceInstance_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentServiceInstance_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTENDPOINT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentEndpoint_ = "";
  /**
   * <pre>
   * The endpoint name of the parent segment.
   * **Endpoint**. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.
   * In a trace segment, the endpoint name is the name of first entry span.
   * </pre>
   *
   * <code>string parentEndpoint = 7;</code>
   * @return The parentEndpoint.
   */
  @java.lang.Override
  public java.lang.String getParentEndpoint() {
    java.lang.Object ref = parentEndpoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentEndpoint_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The endpoint name of the parent segment.
   * **Endpoint**. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.
   * In a trace segment, the endpoint name is the name of first entry span.
   * </pre>
   *
   * <code>string parentEndpoint = 7;</code>
   * @return The bytes for parentEndpoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentEndpointBytes() {
    java.lang.Object ref = parentEndpoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentEndpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORKADDRESSUSEDATPEER_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object networkAddressUsedAtPeer_ = "";
  /**
   * <pre>
   * The network address, including ip/hostname and port, which is used in the client side.
   * Such as Client --&gt; use 127.0.11.8:913 -&gt; Server
   * then, in the reference of entry span reported by Server, the value of this field is 127.0.11.8:913.
   * This plays the important role in the SkyWalking STAM(Streaming Topology Analysis Method)
   * For more details, read https://wu-sheng.github.io/STAM/
   * </pre>
   *
   * <code>string networkAddressUsedAtPeer = 8;</code>
   * @return The networkAddressUsedAtPeer.
   */
  @java.lang.Override
  public java.lang.String getNetworkAddressUsedAtPeer() {
    java.lang.Object ref = networkAddressUsedAtPeer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      networkAddressUsedAtPeer_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The network address, including ip/hostname and port, which is used in the client side.
   * Such as Client --&gt; use 127.0.11.8:913 -&gt; Server
   * then, in the reference of entry span reported by Server, the value of this field is 127.0.11.8:913.
   * This plays the important role in the SkyWalking STAM(Streaming Topology Analysis Method)
   * For more details, read https://wu-sheng.github.io/STAM/
   * </pre>
   *
   * <code>string networkAddressUsedAtPeer = 8;</code>
   * @return The bytes for networkAddressUsedAtPeer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkAddressUsedAtPeerBytes() {
    java.lang.Object ref = networkAddressUsedAtPeer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      networkAddressUsedAtPeer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (refType_ != org.tracing.network.language.tracing.RefType.CrossProcess.getNumber()) {
      output.writeEnum(1, refType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentTraceSegmentId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parentTraceSegmentId_);
    }
    if (parentSpanId_ != 0) {
      output.writeInt32(4, parentSpanId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentService_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parentService_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentServiceInstance_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, parentServiceInstance_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentEndpoint_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, parentEndpoint_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(networkAddressUsedAtPeer_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, networkAddressUsedAtPeer_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (refType_ != org.tracing.network.language.tracing.RefType.CrossProcess.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, refType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentTraceSegmentId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, parentTraceSegmentId_);
    }
    if (parentSpanId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, parentSpanId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentService_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, parentService_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentServiceInstance_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, parentServiceInstance_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentEndpoint_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, parentEndpoint_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(networkAddressUsedAtPeer_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, networkAddressUsedAtPeer_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tracing.network.language.tracing.SegmentReference)) {
      return super.equals(obj);
    }
    org.tracing.network.language.tracing.SegmentReference other = (org.tracing.network.language.tracing.SegmentReference) obj;

    if (refType_ != other.refType_) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getParentTraceSegmentId()
        .equals(other.getParentTraceSegmentId())) return false;
    if (getParentSpanId()
        != other.getParentSpanId()) return false;
    if (!getParentService()
        .equals(other.getParentService())) return false;
    if (!getParentServiceInstance()
        .equals(other.getParentServiceInstance())) return false;
    if (!getParentEndpoint()
        .equals(other.getParentEndpoint())) return false;
    if (!getNetworkAddressUsedAtPeer()
        .equals(other.getNetworkAddressUsedAtPeer())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REFTYPE_FIELD_NUMBER;
    hash = (53 * hash) + refType_;
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + PARENTTRACESEGMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getParentTraceSegmentId().hashCode();
    hash = (37 * hash) + PARENTSPANID_FIELD_NUMBER;
    hash = (53 * hash) + getParentSpanId();
    hash = (37 * hash) + PARENTSERVICE_FIELD_NUMBER;
    hash = (53 * hash) + getParentService().hashCode();
    hash = (37 * hash) + PARENTSERVICEINSTANCE_FIELD_NUMBER;
    hash = (53 * hash) + getParentServiceInstance().hashCode();
    hash = (37 * hash) + PARENTENDPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getParentEndpoint().hashCode();
    hash = (37 * hash) + NETWORKADDRESSUSEDATPEER_FIELD_NUMBER;
    hash = (53 * hash) + getNetworkAddressUsedAtPeer().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.tracing.SegmentReference parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tracing.network.language.tracing.SegmentReference prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Segment reference represents the link between two existing segment.
   * </pre>
   *
   * Protobuf type {@code deeptracing.v1.SegmentReference}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deeptracing.v1.SegmentReference)
      org.tracing.network.language.tracing.SegmentReferenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentReference_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentReference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tracing.network.language.tracing.SegmentReference.class, org.tracing.network.language.tracing.SegmentReference.Builder.class);
    }

    // Construct using org.tracing.network.language.tracing.SegmentReference.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      refType_ = 0;
      traceId_ = "";
      parentTraceSegmentId_ = "";
      parentSpanId_ = 0;
      parentService_ = "";
      parentServiceInstance_ = "";
      parentEndpoint_ = "";
      networkAddressUsedAtPeer_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentReference_descriptor;
    }

    @java.lang.Override
    public org.tracing.network.language.tracing.SegmentReference getDefaultInstanceForType() {
      return org.tracing.network.language.tracing.SegmentReference.getDefaultInstance();
    }

    @java.lang.Override
    public org.tracing.network.language.tracing.SegmentReference build() {
      org.tracing.network.language.tracing.SegmentReference result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tracing.network.language.tracing.SegmentReference buildPartial() {
      org.tracing.network.language.tracing.SegmentReference result = new org.tracing.network.language.tracing.SegmentReference(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.tracing.network.language.tracing.SegmentReference result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.refType_ = refType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.traceId_ = traceId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.parentTraceSegmentId_ = parentTraceSegmentId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.parentSpanId_ = parentSpanId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.parentService_ = parentService_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.parentServiceInstance_ = parentServiceInstance_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.parentEndpoint_ = parentEndpoint_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.networkAddressUsedAtPeer_ = networkAddressUsedAtPeer_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tracing.network.language.tracing.SegmentReference) {
        return mergeFrom((org.tracing.network.language.tracing.SegmentReference)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tracing.network.language.tracing.SegmentReference other) {
      if (other == org.tracing.network.language.tracing.SegmentReference.getDefaultInstance()) return this;
      if (other.refType_ != 0) {
        setRefTypeValue(other.getRefTypeValue());
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getParentTraceSegmentId().isEmpty()) {
        parentTraceSegmentId_ = other.parentTraceSegmentId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getParentSpanId() != 0) {
        setParentSpanId(other.getParentSpanId());
      }
      if (!other.getParentService().isEmpty()) {
        parentService_ = other.parentService_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getParentServiceInstance().isEmpty()) {
        parentServiceInstance_ = other.parentServiceInstance_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getParentEndpoint().isEmpty()) {
        parentEndpoint_ = other.parentEndpoint_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getNetworkAddressUsedAtPeer().isEmpty()) {
        networkAddressUsedAtPeer_ = other.networkAddressUsedAtPeer_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              refType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              parentTraceSegmentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              parentSpanId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              parentService_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              parentServiceInstance_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              parentEndpoint_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              networkAddressUsedAtPeer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int refType_ = 0;
    /**
     * <pre>
     * Represent the reference type. It could be across thread or across process.
     * Across process means there is a downstream RPC call for this.
     * Typically, refType == CrossProcess means SpanObject#spanType = entry.
     * </pre>
     *
     * <code>.deeptracing.v1.RefType refType = 1;</code>
     * @return The enum numeric value on the wire for refType.
     */
    @java.lang.Override public int getRefTypeValue() {
      return refType_;
    }
    /**
     * <pre>
     * Represent the reference type. It could be across thread or across process.
     * Across process means there is a downstream RPC call for this.
     * Typically, refType == CrossProcess means SpanObject#spanType = entry.
     * </pre>
     *
     * <code>.deeptracing.v1.RefType refType = 1;</code>
     * @param value The enum numeric value on the wire for refType to set.
     * @return This builder for chaining.
     */
    public Builder setRefTypeValue(int value) {
      refType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Represent the reference type. It could be across thread or across process.
     * Across process means there is a downstream RPC call for this.
     * Typically, refType == CrossProcess means SpanObject#spanType = entry.
     * </pre>
     *
     * <code>.deeptracing.v1.RefType refType = 1;</code>
     * @return The refType.
     */
    @java.lang.Override
    public org.tracing.network.language.tracing.RefType getRefType() {
      org.tracing.network.language.tracing.RefType result = org.tracing.network.language.tracing.RefType.forNumber(refType_);
      return result == null ? org.tracing.network.language.tracing.RefType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Represent the reference type. It could be across thread or across process.
     * Across process means there is a downstream RPC call for this.
     * Typically, refType == CrossProcess means SpanObject#spanType = entry.
     * </pre>
     *
     * <code>.deeptracing.v1.RefType refType = 1;</code>
     * @param value The refType to set.
     * @return This builder for chaining.
     */
    public Builder setRefType(org.tracing.network.language.tracing.RefType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      refType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Represent the reference type. It could be across thread or across process.
     * Across process means there is a downstream RPC call for this.
     * Typically, refType == CrossProcess means SpanObject#spanType = entry.
     * </pre>
     *
     * <code>.deeptracing.v1.RefType refType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      refType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <pre>
     * A string id represents the whole trace.
     * </pre>
     *
     * <code>string traceId = 2;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A string id represents the whole trace.
     * </pre>
     *
     * <code>string traceId = 2;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A string id represents the whole trace.
     * </pre>
     *
     * <code>string traceId = 2;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A string id represents the whole trace.
     * </pre>
     *
     * <code>string traceId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A string id represents the whole trace.
     * </pre>
     *
     * <code>string traceId = 2;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object parentTraceSegmentId_ = "";
    /**
     * <pre>
     * Another segment id as the parent.
     * </pre>
     *
     * <code>string parentTraceSegmentId = 3;</code>
     * @return The parentTraceSegmentId.
     */
    public java.lang.String getParentTraceSegmentId() {
      java.lang.Object ref = parentTraceSegmentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentTraceSegmentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Another segment id as the parent.
     * </pre>
     *
     * <code>string parentTraceSegmentId = 3;</code>
     * @return The bytes for parentTraceSegmentId.
     */
    public com.google.protobuf.ByteString
        getParentTraceSegmentIdBytes() {
      java.lang.Object ref = parentTraceSegmentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentTraceSegmentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Another segment id as the parent.
     * </pre>
     *
     * <code>string parentTraceSegmentId = 3;</code>
     * @param value The parentTraceSegmentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentTraceSegmentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentTraceSegmentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Another segment id as the parent.
     * </pre>
     *
     * <code>string parentTraceSegmentId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentTraceSegmentId() {
      parentTraceSegmentId_ = getDefaultInstance().getParentTraceSegmentId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Another segment id as the parent.
     * </pre>
     *
     * <code>string parentTraceSegmentId = 3;</code>
     * @param value The bytes for parentTraceSegmentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentTraceSegmentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentTraceSegmentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int parentSpanId_ ;
    /**
     * <pre>
     * The span id in the parent trace segment.
     * </pre>
     *
     * <code>int32 parentSpanId = 4;</code>
     * @return The parentSpanId.
     */
    @java.lang.Override
    public int getParentSpanId() {
      return parentSpanId_;
    }
    /**
     * <pre>
     * The span id in the parent trace segment.
     * </pre>
     *
     * <code>int32 parentSpanId = 4;</code>
     * @param value The parentSpanId to set.
     * @return This builder for chaining.
     */
    public Builder setParentSpanId(int value) {

      parentSpanId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The span id in the parent trace segment.
     * </pre>
     *
     * <code>int32 parentSpanId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentSpanId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      parentSpanId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object parentService_ = "";
    /**
     * <pre>
     * The service logic name of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentService = 5;</code>
     * @return The parentService.
     */
    public java.lang.String getParentService() {
      java.lang.Object ref = parentService_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentService_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The service logic name of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentService = 5;</code>
     * @return The bytes for parentService.
     */
    public com.google.protobuf.ByteString
        getParentServiceBytes() {
      java.lang.Object ref = parentService_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentService_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The service logic name of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentService = 5;</code>
     * @param value The parentService to set.
     * @return This builder for chaining.
     */
    public Builder setParentService(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentService_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The service logic name of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentService = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentService() {
      parentService_ = getDefaultInstance().getParentService();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The service logic name of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentService = 5;</code>
     * @param value The bytes for parentService to set.
     * @return This builder for chaining.
     */
    public Builder setParentServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentService_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object parentServiceInstance_ = "";
    /**
     * <pre>
     * The service logic name instance of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentServiceInstance = 6;</code>
     * @return The parentServiceInstance.
     */
    public java.lang.String getParentServiceInstance() {
      java.lang.Object ref = parentServiceInstance_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentServiceInstance_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The service logic name instance of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentServiceInstance = 6;</code>
     * @return The bytes for parentServiceInstance.
     */
    public com.google.protobuf.ByteString
        getParentServiceInstanceBytes() {
      java.lang.Object ref = parentServiceInstance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentServiceInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The service logic name instance of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentServiceInstance = 6;</code>
     * @param value The parentServiceInstance to set.
     * @return This builder for chaining.
     */
    public Builder setParentServiceInstance(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentServiceInstance_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The service logic name instance of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentServiceInstance = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentServiceInstance() {
      parentServiceInstance_ = getDefaultInstance().getParentServiceInstance();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The service logic name instance of the parent segment.
     * If refType == CrossThread, this name is as same as the trace segment.
     * </pre>
     *
     * <code>string parentServiceInstance = 6;</code>
     * @param value The bytes for parentServiceInstance to set.
     * @return This builder for chaining.
     */
    public Builder setParentServiceInstanceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentServiceInstance_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object parentEndpoint_ = "";
    /**
     * <pre>
     * The endpoint name of the parent segment.
     * **Endpoint**. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.
     * In a trace segment, the endpoint name is the name of first entry span.
     * </pre>
     *
     * <code>string parentEndpoint = 7;</code>
     * @return The parentEndpoint.
     */
    public java.lang.String getParentEndpoint() {
      java.lang.Object ref = parentEndpoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentEndpoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The endpoint name of the parent segment.
     * **Endpoint**. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.
     * In a trace segment, the endpoint name is the name of first entry span.
     * </pre>
     *
     * <code>string parentEndpoint = 7;</code>
     * @return The bytes for parentEndpoint.
     */
    public com.google.protobuf.ByteString
        getParentEndpointBytes() {
      java.lang.Object ref = parentEndpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentEndpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The endpoint name of the parent segment.
     * **Endpoint**. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.
     * In a trace segment, the endpoint name is the name of first entry span.
     * </pre>
     *
     * <code>string parentEndpoint = 7;</code>
     * @param value The parentEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setParentEndpoint(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentEndpoint_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The endpoint name of the parent segment.
     * **Endpoint**. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.
     * In a trace segment, the endpoint name is the name of first entry span.
     * </pre>
     *
     * <code>string parentEndpoint = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentEndpoint() {
      parentEndpoint_ = getDefaultInstance().getParentEndpoint();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The endpoint name of the parent segment.
     * **Endpoint**. A path in a service for incoming requests, such as an HTTP URI path or a gRPC service class + method signature.
     * In a trace segment, the endpoint name is the name of first entry span.
     * </pre>
     *
     * <code>string parentEndpoint = 7;</code>
     * @param value The bytes for parentEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setParentEndpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentEndpoint_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object networkAddressUsedAtPeer_ = "";
    /**
     * <pre>
     * The network address, including ip/hostname and port, which is used in the client side.
     * Such as Client --&gt; use 127.0.11.8:913 -&gt; Server
     * then, in the reference of entry span reported by Server, the value of this field is 127.0.11.8:913.
     * This plays the important role in the SkyWalking STAM(Streaming Topology Analysis Method)
     * For more details, read https://wu-sheng.github.io/STAM/
     * </pre>
     *
     * <code>string networkAddressUsedAtPeer = 8;</code>
     * @return The networkAddressUsedAtPeer.
     */
    public java.lang.String getNetworkAddressUsedAtPeer() {
      java.lang.Object ref = networkAddressUsedAtPeer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        networkAddressUsedAtPeer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The network address, including ip/hostname and port, which is used in the client side.
     * Such as Client --&gt; use 127.0.11.8:913 -&gt; Server
     * then, in the reference of entry span reported by Server, the value of this field is 127.0.11.8:913.
     * This plays the important role in the SkyWalking STAM(Streaming Topology Analysis Method)
     * For more details, read https://wu-sheng.github.io/STAM/
     * </pre>
     *
     * <code>string networkAddressUsedAtPeer = 8;</code>
     * @return The bytes for networkAddressUsedAtPeer.
     */
    public com.google.protobuf.ByteString
        getNetworkAddressUsedAtPeerBytes() {
      java.lang.Object ref = networkAddressUsedAtPeer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkAddressUsedAtPeer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The network address, including ip/hostname and port, which is used in the client side.
     * Such as Client --&gt; use 127.0.11.8:913 -&gt; Server
     * then, in the reference of entry span reported by Server, the value of this field is 127.0.11.8:913.
     * This plays the important role in the SkyWalking STAM(Streaming Topology Analysis Method)
     * For more details, read https://wu-sheng.github.io/STAM/
     * </pre>
     *
     * <code>string networkAddressUsedAtPeer = 8;</code>
     * @param value The networkAddressUsedAtPeer to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkAddressUsedAtPeer(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      networkAddressUsedAtPeer_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The network address, including ip/hostname and port, which is used in the client side.
     * Such as Client --&gt; use 127.0.11.8:913 -&gt; Server
     * then, in the reference of entry span reported by Server, the value of this field is 127.0.11.8:913.
     * This plays the important role in the SkyWalking STAM(Streaming Topology Analysis Method)
     * For more details, read https://wu-sheng.github.io/STAM/
     * </pre>
     *
     * <code>string networkAddressUsedAtPeer = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetworkAddressUsedAtPeer() {
      networkAddressUsedAtPeer_ = getDefaultInstance().getNetworkAddressUsedAtPeer();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The network address, including ip/hostname and port, which is used in the client side.
     * Such as Client --&gt; use 127.0.11.8:913 -&gt; Server
     * then, in the reference of entry span reported by Server, the value of this field is 127.0.11.8:913.
     * This plays the important role in the SkyWalking STAM(Streaming Topology Analysis Method)
     * For more details, read https://wu-sheng.github.io/STAM/
     * </pre>
     *
     * <code>string networkAddressUsedAtPeer = 8;</code>
     * @param value The bytes for networkAddressUsedAtPeer to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkAddressUsedAtPeerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      networkAddressUsedAtPeer_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:deeptracing.v1.SegmentReference)
  }

  // @@protoc_insertion_point(class_scope:deeptracing.v1.SegmentReference)
  private static final org.tracing.network.language.tracing.SegmentReference DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tracing.network.language.tracing.SegmentReference();
  }

  public static org.tracing.network.language.tracing.SegmentReference getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SegmentReference>
      PARSER = new com.google.protobuf.AbstractParser<SegmentReference>() {
    @java.lang.Override
    public SegmentReference parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SegmentReference> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentReference> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tracing.network.language.tracing.SegmentReference getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

