// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracing.proto

package org.tracing.network.language.tracing;

/**
 * <pre>
 * The segment collections for trace report in batch and sync mode.
 * </pre>
 *
 * Protobuf type {@code deeptracing.v1.SegmentCollection}
 */
public final class SegmentCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deeptracing.v1.SegmentCollection)
    SegmentCollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SegmentCollection.newBuilder() to construct.
  private SegmentCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentCollection() {
    segments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SegmentCollection();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentCollection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tracing.network.language.tracing.SegmentCollection.class, org.tracing.network.language.tracing.SegmentCollection.Builder.class);
  }

  public static final int SEGMENTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.tracing.network.language.tracing.SegmentObject> segments_;
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.tracing.network.language.tracing.SegmentObject> getSegmentsList() {
    return segments_;
  }
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.tracing.network.language.tracing.SegmentObjectOrBuilder> 
      getSegmentsOrBuilderList() {
    return segments_;
  }
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  @java.lang.Override
  public int getSegmentsCount() {
    return segments_.size();
  }
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  @java.lang.Override
  public org.tracing.network.language.tracing.SegmentObject getSegments(int index) {
    return segments_.get(index);
  }
  /**
   * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
   */
  @java.lang.Override
  public org.tracing.network.language.tracing.SegmentObjectOrBuilder getSegmentsOrBuilder(
      int index) {
    return segments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < segments_.size(); i++) {
      output.writeMessage(1, segments_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < segments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, segments_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tracing.network.language.tracing.SegmentCollection)) {
      return super.equals(obj);
    }
    org.tracing.network.language.tracing.SegmentCollection other = (org.tracing.network.language.tracing.SegmentCollection) obj;

    if (!getSegmentsList()
        .equals(other.getSegmentsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSegmentsCount() > 0) {
      hash = (37 * hash) + SEGMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getSegmentsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.tracing.SegmentCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tracing.network.language.tracing.SegmentCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The segment collections for trace report in batch and sync mode.
   * </pre>
   *
   * Protobuf type {@code deeptracing.v1.SegmentCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deeptracing.v1.SegmentCollection)
      org.tracing.network.language.tracing.SegmentCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tracing.network.language.tracing.SegmentCollection.class, org.tracing.network.language.tracing.SegmentCollection.Builder.class);
    }

    // Construct using org.tracing.network.language.tracing.SegmentCollection.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
      } else {
        segments_ = null;
        segmentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tracing.network.language.tracing.Tracing.internal_static_deeptracing_v1_SegmentCollection_descriptor;
    }

    @java.lang.Override
    public org.tracing.network.language.tracing.SegmentCollection getDefaultInstanceForType() {
      return org.tracing.network.language.tracing.SegmentCollection.getDefaultInstance();
    }

    @java.lang.Override
    public org.tracing.network.language.tracing.SegmentCollection build() {
      org.tracing.network.language.tracing.SegmentCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tracing.network.language.tracing.SegmentCollection buildPartial() {
      org.tracing.network.language.tracing.SegmentCollection result = new org.tracing.network.language.tracing.SegmentCollection(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.tracing.network.language.tracing.SegmentCollection result) {
      if (segmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          segments_ = java.util.Collections.unmodifiableList(segments_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.segments_ = segments_;
      } else {
        result.segments_ = segmentsBuilder_.build();
      }
    }

    private void buildPartial0(org.tracing.network.language.tracing.SegmentCollection result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tracing.network.language.tracing.SegmentCollection) {
        return mergeFrom((org.tracing.network.language.tracing.SegmentCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tracing.network.language.tracing.SegmentCollection other) {
      if (other == org.tracing.network.language.tracing.SegmentCollection.getDefaultInstance()) return this;
      if (segmentsBuilder_ == null) {
        if (!other.segments_.isEmpty()) {
          if (segments_.isEmpty()) {
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSegmentsIsMutable();
            segments_.addAll(other.segments_);
          }
          onChanged();
        }
      } else {
        if (!other.segments_.isEmpty()) {
          if (segmentsBuilder_.isEmpty()) {
            segmentsBuilder_.dispose();
            segmentsBuilder_ = null;
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00000001);
            segmentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSegmentsFieldBuilder() : null;
          } else {
            segmentsBuilder_.addAllMessages(other.segments_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.tracing.network.language.tracing.SegmentObject m =
                  input.readMessage(
                      org.tracing.network.language.tracing.SegmentObject.parser(),
                      extensionRegistry);
              if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.add(m);
              } else {
                segmentsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.tracing.network.language.tracing.SegmentObject> segments_ =
      java.util.Collections.emptyList();
    private void ensureSegmentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        segments_ = new java.util.ArrayList<org.tracing.network.language.tracing.SegmentObject>(segments_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tracing.network.language.tracing.SegmentObject, org.tracing.network.language.tracing.SegmentObject.Builder, org.tracing.network.language.tracing.SegmentObjectOrBuilder> segmentsBuilder_;

    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public java.util.List<org.tracing.network.language.tracing.SegmentObject> getSegmentsList() {
      if (segmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(segments_);
      } else {
        return segmentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public int getSegmentsCount() {
      if (segmentsBuilder_ == null) {
        return segments_.size();
      } else {
        return segmentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public org.tracing.network.language.tracing.SegmentObject getSegments(int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);
      } else {
        return segmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder setSegments(
        int index, org.tracing.network.language.tracing.SegmentObject value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.set(index, value);
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder setSegments(
        int index, org.tracing.network.language.tracing.SegmentObject.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.set(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder addSegments(org.tracing.network.language.tracing.SegmentObject value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder addSegments(
        int index, org.tracing.network.language.tracing.SegmentObject value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(index, value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder addSegments(
        org.tracing.network.language.tracing.SegmentObject.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder addSegments(
        int index, org.tracing.network.language.tracing.SegmentObject.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder addAllSegments(
        java.lang.Iterable<? extends org.tracing.network.language.tracing.SegmentObject> values) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, segments_);
        onChanged();
      } else {
        segmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder clearSegments() {
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        segmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public Builder removeSegments(int index) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.remove(index);
        onChanged();
      } else {
        segmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public org.tracing.network.language.tracing.SegmentObject.Builder getSegmentsBuilder(
        int index) {
      return getSegmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public org.tracing.network.language.tracing.SegmentObjectOrBuilder getSegmentsOrBuilder(
        int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);  } else {
        return segmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public java.util.List<? extends org.tracing.network.language.tracing.SegmentObjectOrBuilder> 
         getSegmentsOrBuilderList() {
      if (segmentsBuilder_ != null) {
        return segmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(segments_);
      }
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public org.tracing.network.language.tracing.SegmentObject.Builder addSegmentsBuilder() {
      return getSegmentsFieldBuilder().addBuilder(
          org.tracing.network.language.tracing.SegmentObject.getDefaultInstance());
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public org.tracing.network.language.tracing.SegmentObject.Builder addSegmentsBuilder(
        int index) {
      return getSegmentsFieldBuilder().addBuilder(
          index, org.tracing.network.language.tracing.SegmentObject.getDefaultInstance());
    }
    /**
     * <code>repeated .deeptracing.v1.SegmentObject segments = 1;</code>
     */
    public java.util.List<org.tracing.network.language.tracing.SegmentObject.Builder> 
         getSegmentsBuilderList() {
      return getSegmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tracing.network.language.tracing.SegmentObject, org.tracing.network.language.tracing.SegmentObject.Builder, org.tracing.network.language.tracing.SegmentObjectOrBuilder> 
        getSegmentsFieldBuilder() {
      if (segmentsBuilder_ == null) {
        segmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tracing.network.language.tracing.SegmentObject, org.tracing.network.language.tracing.SegmentObject.Builder, org.tracing.network.language.tracing.SegmentObjectOrBuilder>(
                segments_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        segments_ = null;
      }
      return segmentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:deeptracing.v1.SegmentCollection)
  }

  // @@protoc_insertion_point(class_scope:deeptracing.v1.SegmentCollection)
  private static final org.tracing.network.language.tracing.SegmentCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tracing.network.language.tracing.SegmentCollection();
  }

  public static org.tracing.network.language.tracing.SegmentCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SegmentCollection>
      PARSER = new com.google.protobuf.AbstractParser<SegmentCollection>() {
    @java.lang.Override
    public SegmentCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SegmentCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentCollection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tracing.network.language.tracing.SegmentCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

