// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tracing.proto

package org.tracing.network.language.tracing;

public final class Tracing {
  private Tracing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_SegmentObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_SegmentObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_SegmentReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_SegmentReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_SpanObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_SpanObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_Log_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_Log_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_ID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_ID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_SegmentCollection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_SegmentCollection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_SpanAttachedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_SpanAttachedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_SpanAttachedEvent_SpanReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_SpanAttachedEvent_SpanReference_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTracing.proto\022\016deeptracing.v1\032\014Common." +
      "proto\032\rCommand.proto\"\244\001\n\rSegmentObject\022\017" +
      "\n\007traceId\030\001 \001(\t\022\026\n\016traceSegmentId\030\002 \001(\t\022" +
      ")\n\005spans\030\003 \003(\0132\032.deeptracing.v1.SpanObje" +
      "ct\022\017\n\007service\030\004 \001(\t\022\027\n\017serviceInstance\030\005" +
      " \001(\t\022\025\n\risSizeLimited\030\006 \001(\010\"\361\001\n\020SegmentR" +
      "eference\022(\n\007refType\030\001 \001(\0162\027.deeptracing." +
      "v1.RefType\022\017\n\007traceId\030\002 \001(\t\022\034\n\024parentTra" +
      "ceSegmentId\030\003 \001(\t\022\024\n\014parentSpanId\030\004 \001(\005\022" +
      "\025\n\rparentService\030\005 \001(\t\022\035\n\025parentServiceI" +
      "nstance\030\006 \001(\t\022\026\n\016parentEndpoint\030\007 \001(\t\022 \n" +
      "\030networkAddressUsedAtPeer\030\010 \001(\t\"\226\003\n\nSpan" +
      "Object\022\016\n\006spanId\030\001 \001(\005\022\024\n\014parentSpanId\030\002" +
      " \001(\005\022\021\n\tstartTime\030\003 \001(\003\022\017\n\007endTime\030\004 \001(\003" +
      "\022.\n\004refs\030\005 \003(\0132 .deeptracing.v1.SegmentR" +
      "eference\022\025\n\roperationName\030\006 \001(\t\022\014\n\004peer\030" +
      "\007 \001(\t\022*\n\010spanType\030\010 \001(\0162\030.deeptracing.v1" +
      ".SpanType\022,\n\tspanLayer\030\t \001(\0162\031.deeptraci" +
      "ng.v1.SpanLayer\022\023\n\013componentId\030\n \001(\005\022\017\n\007" +
      "isError\030\013 \001(\010\0220\n\004tags\030\014 \003(\0132\".deeptracin" +
      "g.v1.KeyStringValuePair\022!\n\004logs\030\r \003(\0132\023." +
      "deeptracing.v1.Log\022\024\n\014skipAnalysis\030\016 \001(\010" +
      "\"E\n\003Log\022\014\n\004time\030\001 \001(\003\0220\n\004data\030\002 \003(\0132\".de" +
      "eptracing.v1.KeyStringValuePair\"\020\n\002ID\022\n\n" +
      "\002id\030\001 \003(\t\"D\n\021SegmentCollection\022/\n\010segmen" +
      "ts\030\001 \003(\0132\035.deeptracing.v1.SegmentObject\"" +
      "\342\003\n\021SpanAttachedEvent\022*\n\tstartTime\030\001 \001(\013" +
      "2\027.deeptracing.v1.Instant\022\r\n\005event\030\002 \001(\t" +
      "\022(\n\007endTime\030\003 \001(\0132\027.deeptracing.v1.Insta" +
      "nt\0220\n\004tags\030\004 \003(\0132\".deeptracing.v1.KeyStr" +
      "ingValuePair\0220\n\007summary\030\005 \003(\0132\037.deeptrac" +
      "ing.v1.KeyIntValuePair\022E\n\014traceContext\030\006" +
      " \001(\0132/.deeptracing.v1.SpanAttachedEvent." +
      "SpanReference\032\213\001\n\rSpanReference\022A\n\004type\030" +
      "\001 \001(\01623.deeptracing.v1.SpanAttachedEvent" +
      ".SpanReferenceType\022\017\n\007traceId\030\002 \001(\t\022\026\n\016t" +
      "raceSegmentId\030\003 \001(\t\022\016\n\006spanId\030\004 \001(\t\"/\n\021S" +
      "panReferenceType\022\016\n\nSKYWALKING\020\000\022\n\n\006ZIPK" +
      "IN\020\001**\n\010SpanType\022\t\n\005Entry\020\000\022\010\n\004Exit\020\001\022\t\n" +
      "\005Local\020\002*,\n\007RefType\022\020\n\014CrossProcess\020\000\022\017\n" +
      "\013CrossThread\020\001*_\n\tSpanLayer\022\013\n\007Unknown\020\000" +
      "\022\014\n\010Database\020\001\022\020\n\014RPCFramework\020\002\022\010\n\004Http" +
      "\020\003\022\006\n\002MQ\020\004\022\t\n\005Cache\020\005\022\010\n\004FAAS\020\0062l\n\036SpanA" +
      "ttachedEventReportService\022J\n\007collect\022!.d" +
      "eeptracing.v1.SpanAttachedEvent\032\030.deeptr" +
      "acing.v1.Commands\"\000(\001B\204\001\n$org.tracing.ne" +
      "twork.language.tracingP\001Z:skywalking.apa" +
      "che.org/repo/goapi/collect/language/agen" +
      "t/v3\252\002\035SkyWalking.NetworkProtocol.V3b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tracing.network.language.common.Common.getDescriptor(),
          org.tracing.network.language.common.CommandOuterClass.getDescriptor(),
        });
    internal_static_deeptracing_v1_SegmentObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_deeptracing_v1_SegmentObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_SegmentObject_descriptor,
        new java.lang.String[] { "TraceId", "TraceSegmentId", "Spans", "Service", "ServiceInstance", "IsSizeLimited", });
    internal_static_deeptracing_v1_SegmentReference_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_deeptracing_v1_SegmentReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_SegmentReference_descriptor,
        new java.lang.String[] { "RefType", "TraceId", "ParentTraceSegmentId", "ParentSpanId", "ParentService", "ParentServiceInstance", "ParentEndpoint", "NetworkAddressUsedAtPeer", });
    internal_static_deeptracing_v1_SpanObject_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_deeptracing_v1_SpanObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_SpanObject_descriptor,
        new java.lang.String[] { "SpanId", "ParentSpanId", "StartTime", "EndTime", "Refs", "OperationName", "Peer", "SpanType", "SpanLayer", "ComponentId", "IsError", "Tags", "Logs", "SkipAnalysis", });
    internal_static_deeptracing_v1_Log_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_deeptracing_v1_Log_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_Log_descriptor,
        new java.lang.String[] { "Time", "Data", });
    internal_static_deeptracing_v1_ID_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_deeptracing_v1_ID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_ID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_deeptracing_v1_SegmentCollection_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_deeptracing_v1_SegmentCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_SegmentCollection_descriptor,
        new java.lang.String[] { "Segments", });
    internal_static_deeptracing_v1_SpanAttachedEvent_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_deeptracing_v1_SpanAttachedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_SpanAttachedEvent_descriptor,
        new java.lang.String[] { "StartTime", "Event", "EndTime", "Tags", "Summary", "TraceContext", });
    internal_static_deeptracing_v1_SpanAttachedEvent_SpanReference_descriptor =
      internal_static_deeptracing_v1_SpanAttachedEvent_descriptor.getNestedTypes().get(0);
    internal_static_deeptracing_v1_SpanAttachedEvent_SpanReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_SpanAttachedEvent_SpanReference_descriptor,
        new java.lang.String[] { "Type", "TraceId", "TraceSegmentId", "SpanId", });
    org.tracing.network.language.common.Common.getDescriptor();
    org.tracing.network.language.common.CommandOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
