// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package org.tracing.network.language.common;

/**
 * <pre>
 * Transferring multiple Command in agent and OAP.
 * </pre>
 *
 * Protobuf type {@code deeptracing.v1.Commands}
 */
public final class Commands extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deeptracing.v1.Commands)
    CommandsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Commands.newBuilder() to construct.
  private Commands(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Commands() {
    commands_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Commands();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tracing.network.language.common.CommandOuterClass.internal_static_deeptracing_v1_Commands_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tracing.network.language.common.CommandOuterClass.internal_static_deeptracing_v1_Commands_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tracing.network.language.common.Commands.class, org.tracing.network.language.common.Commands.Builder.class);
  }

  public static final int COMMANDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.tracing.network.language.common.Command> commands_;
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.tracing.network.language.common.Command> getCommandsList() {
    return commands_;
  }
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.tracing.network.language.common.CommandOrBuilder> 
      getCommandsOrBuilderList() {
    return commands_;
  }
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  @java.lang.Override
  public int getCommandsCount() {
    return commands_.size();
  }
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  @java.lang.Override
  public org.tracing.network.language.common.Command getCommands(int index) {
    return commands_.get(index);
  }
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  @java.lang.Override
  public org.tracing.network.language.common.CommandOrBuilder getCommandsOrBuilder(
      int index) {
    return commands_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < commands_.size(); i++) {
      output.writeMessage(1, commands_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < commands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, commands_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tracing.network.language.common.Commands)) {
      return super.equals(obj);
    }
    org.tracing.network.language.common.Commands other = (org.tracing.network.language.common.Commands) obj;

    if (!getCommandsList()
        .equals(other.getCommandsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCommandsCount() > 0) {
      hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getCommandsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tracing.network.language.common.Commands parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.common.Commands parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.common.Commands parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.common.Commands parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.common.Commands parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tracing.network.language.common.Commands parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tracing.network.language.common.Commands parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.common.Commands parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tracing.network.language.common.Commands parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.common.Commands parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tracing.network.language.common.Commands parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tracing.network.language.common.Commands parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tracing.network.language.common.Commands prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Transferring multiple Command in agent and OAP.
   * </pre>
   *
   * Protobuf type {@code deeptracing.v1.Commands}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deeptracing.v1.Commands)
      org.tracing.network.language.common.CommandsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tracing.network.language.common.CommandOuterClass.internal_static_deeptracing_v1_Commands_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tracing.network.language.common.CommandOuterClass.internal_static_deeptracing_v1_Commands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tracing.network.language.common.Commands.class, org.tracing.network.language.common.Commands.Builder.class);
    }

    // Construct using org.tracing.network.language.common.Commands.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
      } else {
        commands_ = null;
        commandsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tracing.network.language.common.CommandOuterClass.internal_static_deeptracing_v1_Commands_descriptor;
    }

    @java.lang.Override
    public org.tracing.network.language.common.Commands getDefaultInstanceForType() {
      return org.tracing.network.language.common.Commands.getDefaultInstance();
    }

    @java.lang.Override
    public org.tracing.network.language.common.Commands build() {
      org.tracing.network.language.common.Commands result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tracing.network.language.common.Commands buildPartial() {
      org.tracing.network.language.common.Commands result = new org.tracing.network.language.common.Commands(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.tracing.network.language.common.Commands result) {
      if (commandsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          commands_ = java.util.Collections.unmodifiableList(commands_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.commands_ = commands_;
      } else {
        result.commands_ = commandsBuilder_.build();
      }
    }

    private void buildPartial0(org.tracing.network.language.common.Commands result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tracing.network.language.common.Commands) {
        return mergeFrom((org.tracing.network.language.common.Commands)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tracing.network.language.common.Commands other) {
      if (other == org.tracing.network.language.common.Commands.getDefaultInstance()) return this;
      if (commandsBuilder_ == null) {
        if (!other.commands_.isEmpty()) {
          if (commands_.isEmpty()) {
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCommandsIsMutable();
            commands_.addAll(other.commands_);
          }
          onChanged();
        }
      } else {
        if (!other.commands_.isEmpty()) {
          if (commandsBuilder_.isEmpty()) {
            commandsBuilder_.dispose();
            commandsBuilder_ = null;
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000001);
            commandsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCommandsFieldBuilder() : null;
          } else {
            commandsBuilder_.addAllMessages(other.commands_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.tracing.network.language.common.Command m =
                  input.readMessage(
                      org.tracing.network.language.common.Command.parser(),
                      extensionRegistry);
              if (commandsBuilder_ == null) {
                ensureCommandsIsMutable();
                commands_.add(m);
              } else {
                commandsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.tracing.network.language.common.Command> commands_ =
      java.util.Collections.emptyList();
    private void ensureCommandsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        commands_ = new java.util.ArrayList<org.tracing.network.language.common.Command>(commands_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tracing.network.language.common.Command, org.tracing.network.language.common.Command.Builder, org.tracing.network.language.common.CommandOrBuilder> commandsBuilder_;

    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public java.util.List<org.tracing.network.language.common.Command> getCommandsList() {
      if (commandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(commands_);
      } else {
        return commandsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public int getCommandsCount() {
      if (commandsBuilder_ == null) {
        return commands_.size();
      } else {
        return commandsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public org.tracing.network.language.common.Command getCommands(int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);
      } else {
        return commandsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder setCommands(
        int index, org.tracing.network.language.common.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.set(index, value);
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder setCommands(
        int index, org.tracing.network.language.common.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.set(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder addCommands(org.tracing.network.language.common.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder addCommands(
        int index, org.tracing.network.language.common.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(index, value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder addCommands(
        org.tracing.network.language.common.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder addCommands(
        int index, org.tracing.network.language.common.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder addAllCommands(
        java.lang.Iterable<? extends org.tracing.network.language.common.Command> values) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commands_);
        onChanged();
      } else {
        commandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder clearCommands() {
      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        commandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public Builder removeCommands(int index) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.remove(index);
        onChanged();
      } else {
        commandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public org.tracing.network.language.common.Command.Builder getCommandsBuilder(
        int index) {
      return getCommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public org.tracing.network.language.common.CommandOrBuilder getCommandsOrBuilder(
        int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);  } else {
        return commandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public java.util.List<? extends org.tracing.network.language.common.CommandOrBuilder> 
         getCommandsOrBuilderList() {
      if (commandsBuilder_ != null) {
        return commandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(commands_);
      }
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public org.tracing.network.language.common.Command.Builder addCommandsBuilder() {
      return getCommandsFieldBuilder().addBuilder(
          org.tracing.network.language.common.Command.getDefaultInstance());
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public org.tracing.network.language.common.Command.Builder addCommandsBuilder(
        int index) {
      return getCommandsFieldBuilder().addBuilder(
          index, org.tracing.network.language.common.Command.getDefaultInstance());
    }
    /**
     * <code>repeated .deeptracing.v1.Command commands = 1;</code>
     */
    public java.util.List<org.tracing.network.language.common.Command.Builder> 
         getCommandsBuilderList() {
      return getCommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tracing.network.language.common.Command, org.tracing.network.language.common.Command.Builder, org.tracing.network.language.common.CommandOrBuilder> 
        getCommandsFieldBuilder() {
      if (commandsBuilder_ == null) {
        commandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tracing.network.language.common.Command, org.tracing.network.language.common.Command.Builder, org.tracing.network.language.common.CommandOrBuilder>(
                commands_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        commands_ = null;
      }
      return commandsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:deeptracing.v1.Commands)
  }

  // @@protoc_insertion_point(class_scope:deeptracing.v1.Commands)
  private static final org.tracing.network.language.common.Commands DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tracing.network.language.common.Commands();
  }

  public static org.tracing.network.language.common.Commands getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Commands>
      PARSER = new com.google.protobuf.AbstractParser<Commands>() {
    @java.lang.Override
    public Commands parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Commands> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Commands> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tracing.network.language.common.Commands getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

