// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package org.tracing.network.language.common;

public final class CommandOuterClass {
  private CommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deeptracing_v1_Commands_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deeptracing_v1_Commands_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\016deeptracing.v1\032\014Common." +
      "proto\"L\n\007Command\022\017\n\007command\030\001 \001(\t\0220\n\004arg" +
      "s\030\002 \003(\0132\".deeptracing.v1.KeyStringValueP" +
      "air\"5\n\010Commands\022)\n\010commands\030\001 \003(\0132\027.deep" +
      "tracing.v1.CommandB{\n#org.tracing.networ" +
      "k.language.commonP\001Z2skywalking.apache.o" +
      "rg/repo/goapi/collect/common/v3\252\002\035SkyWal" +
      "king.NetworkProtocol.V3b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tracing.network.language.common.Common.getDescriptor(),
        });
    internal_static_deeptracing_v1_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_deeptracing_v1_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_Command_descriptor,
        new java.lang.String[] { "Command", "Args", });
    internal_static_deeptracing_v1_Commands_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_deeptracing_v1_Commands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deeptracing_v1_Commands_descriptor,
        new java.lang.String[] { "Commands", });
    org.tracing.network.language.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
