// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package org.tracing.network.language.common;

public interface CommandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.Commands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  java.util.List<org.tracing.network.language.common.Command> 
      getCommandsList();
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  org.tracing.network.language.common.Command getCommands(int index);
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  java.util.List<? extends org.tracing.network.language.common.CommandOrBuilder> 
      getCommandsOrBuilderList();
  /**
   * <code>repeated .deeptracing.v1.Command commands = 1;</code>
   */
  org.tracing.network.language.common.CommandOrBuilder getCommandsOrBuilder(
      int index);
}
