// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package org.tracing.network.language.common;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Use command name to distinguish different data type.
   * </pre>
   *
   * <code>string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <pre>
   * Use command name to distinguish different data type.
   * </pre>
   *
   * <code>string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <pre>
   * Data content in command.
   * The value of content needs to be serialized as string for transmission.
   *
   * Basic data type: convert as string.
   * The list of basic data: multiple data are split by ",".
   * Complex data: serialize string through json.
   * </pre>
   *
   * <code>repeated .deeptracing.v1.KeyStringValuePair args = 2;</code>
   */
  java.util.List<org.tracing.network.language.common.KeyStringValuePair> 
      getArgsList();
  /**
   * <pre>
   * Data content in command.
   * The value of content needs to be serialized as string for transmission.
   *
   * Basic data type: convert as string.
   * The list of basic data: multiple data are split by ",".
   * Complex data: serialize string through json.
   * </pre>
   *
   * <code>repeated .deeptracing.v1.KeyStringValuePair args = 2;</code>
   */
  org.tracing.network.language.common.KeyStringValuePair getArgs(int index);
  /**
   * <pre>
   * Data content in command.
   * The value of content needs to be serialized as string for transmission.
   *
   * Basic data type: convert as string.
   * The list of basic data: multiple data are split by ",".
   * Complex data: serialize string through json.
   * </pre>
   *
   * <code>repeated .deeptracing.v1.KeyStringValuePair args = 2;</code>
   */
  int getArgsCount();
  /**
   * <pre>
   * Data content in command.
   * The value of content needs to be serialized as string for transmission.
   *
   * Basic data type: convert as string.
   * The list of basic data: multiple data are split by ",".
   * Complex data: serialize string through json.
   * </pre>
   *
   * <code>repeated .deeptracing.v1.KeyStringValuePair args = 2;</code>
   */
  java.util.List<? extends org.tracing.network.language.common.KeyStringValuePairOrBuilder> 
      getArgsOrBuilderList();
  /**
   * <pre>
   * Data content in command.
   * The value of content needs to be serialized as string for transmission.
   *
   * Basic data type: convert as string.
   * The list of basic data: multiple data are split by ",".
   * Complex data: serialize string through json.
   * </pre>
   *
   * <code>repeated .deeptracing.v1.KeyStringValuePair args = 2;</code>
   */
  org.tracing.network.language.common.KeyStringValuePairOrBuilder getArgsOrBuilder(
      int index);
}
