// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package org.tracing.network.language.common;

public interface CPUOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.CPU)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double usagePercent = 2;</code>
   * @return The usagePercent.
   */
  double getUsagePercent();
}
