// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package org.tracing.network.language.common;

public interface InstantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.Instant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The number of seconds from the epoch of 1970-01-01T00:00:00Z.
   * </pre>
   *
   * <code>int64 seconds = 1;</code>
   * @return The seconds.
   */
  long getSeconds();

  /**
   * <pre>
   * The number of nanoseconds, later along the time-line, from the seconds field.
   * This is always positive, and never exceeds 999,999,999.
   * </pre>
   *
   * <code>int32 nanos = 2;</code>
   * @return The nanos.
   */
  int getNanos();
}
