// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package org.tracing.network.language.common;

public interface KeyIntValuePairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deeptracing.v1.KeyIntValuePair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>int64 value = 2;</code>
   * @return The value.
   */
  long getValue();
}
